/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from './ERC20';
export type { Proxy } from './Proxy';
export * as factories from './factories';
export { ERC20__factory } from './factories/ERC20__factory';
export { Proxy__factory } from './factories/Proxy__factory';
